// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABuQR6WJ_D5KKoIU3JJeq8yZ5DsE9OphQ',
    appId: '1:8574803772:web:b70bb7639b4ce43539c839',
    messagingSenderId: '8574803772',
    projectId: 'campusq-d754c',
    authDomain: 'campusq-d754c.firebaseapp.com',
    storageBucket: 'campusq-d754c.firebasestorage.app',
    measurementId: 'G-MDGP299PPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiopl-Ihv5rqRZqdeVsazNl9G91Qr6Qjw',
    appId: '1:8574803772:android:8157795f6129412539c839',
    messagingSenderId: '8574803772',
    projectId: 'campusq-d754c',
    storageBucket: 'campusq-d754c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp11awW89jTf9NdD6mZ3RKqbXS70HZxPg',
    appId: '1:8574803772:ios:4699afe31571154b39c839',
    messagingSenderId: '8574803772',
    projectId: 'campusq-d754c',
    storageBucket: 'campusq-d754c.firebasestorage.app',
    iosBundleId: 'com.example.hciProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp11awW89jTf9NdD6mZ3RKqbXS70HZxPg',
    appId: '1:8574803772:ios:4699afe31571154b39c839',
    messagingSenderId: '8574803772',
    projectId: 'campusq-d754c',
    storageBucket: 'campusq-d754c.firebasestorage.app',
    iosBundleId: 'com.example.hciProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABuQR6WJ_D5KKoIU3JJeq8yZ5DsE9OphQ',
    appId: '1:8574803772:web:73f3634343c463f139c839',
    messagingSenderId: '8574803772',
    projectId: 'campusq-d754c',
    authDomain: 'campusq-d754c.firebaseapp.com',
    storageBucket: 'campusq-d754c.firebasestorage.app',
    measurementId: 'G-RXTF817CJ5',
  );

}